hash-format = "sha256"

[[files]]
file = "config/fabrication/dimensional_tools.ini"
hash = "14eb4e8cd105c580403c4e5bc6bba831c81aedcf4e6e04485c74e9d3f253689f"

[[files]]
file = "config/fabrication/features.ini"
hash = "2590c58422249f3d98ef4a2336afb85c4a00438ce735fcc2a3c9cce859aa704f"

[[files]]
file = "config/fabrication/gear_components.ini"
hash = "5a9291467f9f7918687a0d138a61e396cb9299b0b4ea2e4cf4f4d6f3594f865b"

[[files]]
file = "config/fabrication/item_despawn.ini"
hash = "24b26ac0b8ff13889b6b3b00b2309366eb72c36014a9679a82f4cbff46c275f4"

[[files]]
file = "config/fabrication/taggable_players.ini"
hash = "fe069b4316f910f2f3b703cedd9930b73eed74c2ae86909f8b43a8ffd3d1af45"

[[files]]
file = "config/fabrication/yeet_recipes.ini"
hash = "939cfc95ed4a7480ac08d3f692538a348af72c6db693349c61f93f926976d1f2"

[[files]]
file = "config/styled-chat.json"
hash = "53401ca7bf44f10d9c0ba90c3097a6f249c9d8fc4cfd7bf1daa56a1e3965b8b5"

[[files]]
file = "config/styled-nicknames.json"
hash = "6653b6973a0085957c3b512460e0889de829a05cd70d91bfd989180baf1c4c11"

[[files]]
file = "config/styledplayerlist/config.json"
hash = "85cc06508645172c4aa9c18691235209bcd1c8eb892ad418e6bdfd4654eee818"

[[files]]
file = "config/styledplayerlist/styles/animated.json"
hash = "9c86b4c00b2dc199e13cd4278961d004f413ef0468a10a1faa70892bd65b8f26"

[[files]]
file = "config/styledplayerlist/styles/default.json"
hash = "29c2996ddd9b1796f105e83d6d9517723d0e0e0986e7bbdc69eeb7b010d6835f"

[[files]]
file = "config/universal-graves/config.json"
hash = "cc57f9c56206a71fc7c9145d620882f7fdaada18753811decf74a1d33f8b3ce9"

[[files]]
file = "config/universal-graves/models/example.json"
hash = "9e9363b1ffafbb1dd8b9c53c77311eddb37697ca48d3b287291ff5573fe48352"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/beenfo.pw.toml"
hash = "36573ec78f4faa00770337200cddb801e61217392513913d15a36da0ed95edab"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "095a93b4f0b4e2b8fadf8359bc145cbdd83be3c5bf23432e9a5f4e54d60de5b4"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/cropped.pw.toml"
hash = "89a281632f1303d96b11e51a30dc5d63db7ae6b345789eea24933c063b1131da"
metafile = true

[[files]]
file = "mods/deepslatecutting.pw.toml"
hash = "f189746778654d05f2f568cb23d3a6ea50c25b7c0f490c1091b77e2eb60327d9"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
hash = "a4c26b997a50b2db668863350bba9264519d537fe0ed1f489a64b4dc004082ed"
metafile = true

[[files]]
file = "mods/invview.pw.toml"
hash = "3b822e0fb2de224353aa4e99af208648df864163623ac22c38456280fdb04245"
metafile = true

[[files]]
file = "mods/itemrename.pw.toml"
hash = "f5ec4a1f805c364e2ec296faa008f515731d277900743e74974fac528715cdf0"
metafile = true

[[files]]
file = "mods/jumpvader.pw.toml"
hash = "ddcbfa0838b5ff8dcf4d7d2cad598a158f65e84db8e8e77929f6041c9ffd66b1"
metafile = true

[[files]]
file = "mods/leaves-us-in-peace.pw.toml"
hash = "215952f46cdc0e8f381d4d448614ce0284426e3f0cbbc8d3a8c2841b9493fedf"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "84defc8f8116d5c0e4210934ed1f555641a1db71b767fa4beddee21c47118868"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "7fa8795248f8813dbda62b9ef3e3f718368857ad1b0498362ea11bb1399bd229"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "3c5a5fe2267f93188d7e41f7a06ea09a64b40224b90f601e42cf666c16f12268"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "803e0a9f2b35d933bc3d583ce4db52dfff9c717b7f89f4462f0437f16b86e6fc"
metafile = true

[[files]]
file = "mods/polysit.pw.toml"
hash = "9e28be7f65522422a4ae6de4b75a6ae539067fdeae63f8c000641ac66925fb33"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "2c15a7ba78e8d8abbc612e55cfdb3df7c002a90d8fa467d88e28fe875ccaa3e9"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "f2644c0b7c14e9f76afc4e042970f010636e98a116ed92e624e87f01a782aab6"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "5e78027ca7fa10fb5ca74614dae6941696f7db526afb36f678df75a636cf8739"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f010bbe486733738e92241d10f403e28a8feeb40b45ec3af3b2270523f955216"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "e079fd37c41a102621a9d3ee5b8cdbc332fd28ec007a28a019d30b35d3829b41"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "e6f4e06c4d4442c08a9f64772a3e078209d57a5d81f6c8ee0fde0da006789a3a"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "8a6442ca759237fb4346e02653feba023529db29127c6b20740801199395241d"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "c7a5a9c7e113c4ee32c2f0f779ee609a138d9855a8adaca00fb36fcdc8f7066a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "82f2482d9c8e39dbdc8cf303866d7fb087861aec2a0b5564ce7fc37caf274750"
metafile = true

[[files]]
file = "mods/veindigging.pw.toml"
hash = "18665e1421d5742b69f1524fa0fdd5f4a8382146204510b8bd5619c11ead3e25"
metafile = true
