name = "vsixmc"
author = "leo60228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3e8bb09ad1953abf09e685b1f1fdedd8187ce5593b8a4a29fb2caa257622737"

[versions]
minecraft = "1.20.1"
quilt = "0.29.3-beta.1"
